//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02_Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C02_Members()
        {
            this.C06_UserPermisRelationship = new HashSet<C06_UserPermisRelationship>();
            this.C08_Timesheet = new HashSet<C08_Timesheet>();
            this.C03_ProjectMembers = new HashSet<C03_ProjectMembers>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Leader { get; set; }
        public string Email { get; set; }
        public Nullable<int> Descipline { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> Deactived { get; set; }
        public Nullable<bool> SystemMember { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C06_UserPermisRelationship> C06_UserPermisRelationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C08_Timesheet> C08_Timesheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C03_ProjectMembers> C03_ProjectMembers { get; set; }
    }
}
