//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C03_ProjectMembers
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ChuTriChinh { get; set; }
        public Nullable<int> ChuTriKienTruc { get; set; }
        public Nullable<int> ChuTriKetCau { get; set; }
        public Nullable<int> ChuTriMEP { get; set; }
        public Nullable<int> BIMManager { get; set; }
        public Nullable<int> LegalManager { get; set; }
        public Nullable<int> Admin { get; set; }
        public Nullable<int> ChuTriKienTruc2 { get; set; }
        public Nullable<int> ChuTriKetCau2 { get; set; }
        public Nullable<int> ChuTriMEP2 { get; set; }
        public Nullable<int> LegalManager2 { get; set; }
        public string ThanhVienKhac { get; set; }
    
        public virtual C01_Projects C01_Projects { get; set; }
        public virtual C02_Members C02_Members { get; set; }
    }
}
