//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C05_PermissionDetail
    {
        public int id_detail { get; set; }
        public Nullable<int> id_per { get; set; }
        public string Action_Name { get; set; }
        public string Action_code { get; set; }
    
        public virtual C04_Permission C04_Permission { get; set; }
    }
}
