//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C14_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C14_Services()
        {
            this.C15_SubConServices = new HashSet<C15_SubConServices>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ServiceGroupId { get; set; }
    
        public virtual C22_ServiceGroup C22_ServiceGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C15_SubConServices> C15_SubConServices { get; set; }
    }
}
