//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C15_SubConServices
    {
        public int Id { get; set; }
        public Nullable<int> SubConId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual C12_SubContractor C12_SubContractor { get; set; }
        public virtual C14_Services C14_Services { get; set; }
    }
}
