//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C21_DetailAction
    {
        public int Id { get; set; }
        public Nullable<int> WorktypeId { get; set; }
        public string DetailAction { get; set; }
        public string Note { get; set; }
    
        public virtual C07_WorkType C07_WorkType { get; set; }
    }
}
