//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C24_ChangedOrder
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string CO_Number { get; set; }
        public string CO_Resource { get; set; }
        public string CO_Description { get; set; }
        public Nullable<int> CO_Descipline { get; set; }
        public Nullable<decimal> CO_TotalCost { get; set; }
        public Nullable<System.DateTime> CO_TimeSpend { get; set; }
        public Nullable<decimal> CO_LabourCost { get; set; }
        public Nullable<decimal> CO_MaterialCost { get; set; }
        public Nullable<decimal> CO_EquipmentCost { get; set; }
        public Nullable<System.DateTime> CO_DelayTime { get; set; }
    }
}
