//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C99_ActivityLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DatetimeCreate { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Scope { get; set; }
        public string Details { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
