//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dmcDbcontext : DbContext
    {
        public dmcDbcontext()
            : base("name=dmcDbcontext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C01_Projects> C01_Projects { get; set; }
        public virtual DbSet<C03_ProjectMembers> C03_ProjectMembers { get; set; }
        public virtual DbSet<C04_Permission> C04_Permission { get; set; }
        public virtual DbSet<C05_PermissionDetail> C05_PermissionDetail { get; set; }
        public virtual DbSet<C06_UserPermisRelationship> C06_UserPermisRelationship { get; set; }
        public virtual DbSet<C02_Members> C02_Members { get; set; }
    }
}
