//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCTimesheet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dmcDbcontext : DbContext
    {
        public dmcDbcontext()
            : base("name=dmcDbcontext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C01_Projects> C01_Projects { get; set; }
        public virtual DbSet<C02_Members> C02_Members { get; set; }
        public virtual DbSet<C03_ProjectMembers> C03_ProjectMembers { get; set; }
        public virtual DbSet<C04_Permission> C04_Permission { get; set; }
        public virtual DbSet<C05_PermissionDetail> C05_PermissionDetail { get; set; }
        public virtual DbSet<C06_UserPermisRelationship> C06_UserPermisRelationship { get; set; }
        public virtual DbSet<C07_WorkType> C07_WorkType { get; set; }
        public virtual DbSet<C08_Timesheet> C08_Timesheet { get; set; }
        public virtual DbSet<C09_ProjectSubCon> C09_ProjectSubCon { get; set; }
        public virtual DbSet<C10_Owner> C10_Owner { get; set; }
        public virtual DbSet<C11_Location> C11_Location { get; set; }
        public virtual DbSet<C12_SubContractor> C12_SubContractor { get; set; }
        public virtual DbSet<C13_ProjectType> C13_ProjectType { get; set; }
        public virtual DbSet<C14_Services> C14_Services { get; set; }
        public virtual DbSet<C15_SubConServices> C15_SubConServices { get; set; }
        public virtual DbSet<C16_Status> C16_Status { get; set; }
        public virtual DbSet<C17_Position> C17_Position { get; set; }
        public virtual DbSet<C18_Descipline> C18_Descipline { get; set; }
    }
}
